sdm845-common: fingerprint: Add blank callbacks for udfps
Without this, build will throw error below:

device/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:209:25: error: allocating an object of abstract class type 'android::hardware::biometrics::fingerprint::V2_3::implementation::BiometricsFingerprint'
        sInstance = new BiometricsFingerprint();
                        ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:214:47: note: unimplemented pure virtual method 'onShowUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onShowUdfpsOverlay() = 0;
                                              ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:219:47: note: unimplemented pure virtual method 'onHideUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onHideUdfpsOverlay() = 0;
                                              ^
since we have no under display fingerprint sensor, let's just satisfy it with blank callbacks.

Signed-off-by: Andrey Sprynga <rtx4d@aospa.co>
Change-Id: I1ee7ab2796922ed3a381a802cc55d1f6bd9eb87f